apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbox
  template:
    metadata:
      labels: 
        app: sbox
        #version: v1
    spec:
      containers:
      - name: sbox
        image: localhost:5000/sbox
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
        env:
          - name: HASHTAG
            valueFrom:
              secretKeyRef:
                name: twitter-apikey
                key: HASHTAG
          - name: TWITTER_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: twitter-apikey
                key: TWITTER_CONSUMER_KEY
          - name: TWITTER_CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter-apikey
                key: TWITTER_CONSUMER_SECRET
          - name: TWITTER_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: twitter-apikey
                key: TWITTER_ACCESS_TOKEN
          - name: TWITTER_ACCESS_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter-apikey
                key: TWITTER_ACCESS_TOKEN_SECRET
      volumes:
      - name: docker-volume
        hostPath:
          # directory location on host
          path: /var/run/docker.sock
          # this field is optional
          type: Socket
---
